pt-qiandao:
  cookies_path: '/ptqiandao/cookies_files/'
  image_captcha_save_path: '/ptqiandao/imageCaptcha/'
  sites:
    - site_name: '海棠(htpt)'
      index_url: 'https://www.htpt.cc/index.php'
      index_url_str: 'index'
      index_btn_xpath: '//*[@id="mainmenu"]/li[1]/a'
      login_url: 'https://www.htpt.cc/login.php'
      login_url_str: 'login'
      username_input_xpath: '/html/body/table[2]/tbody/tr/td/form[2]/table/tbody/tr[1]/td[2]/input'
      password_input_xpath: '/html/body/table[2]/tbody/tr/td/form[2]/table/tbody/tr[2]/td[2]/input'
      submit_btn_xpath: '/html/body/table[2]/tbody/tr/td/form[2]/table/tbody/tr[7]/td/input[1]'
      attendance_btn_xpath: '//*[@id="info_block"]/tbody/tr/td/table/tbody/tr/td[1]/span/a[5]'
      attendance_text: '签到'
      attendance_result_xpath: '//*[@id="info_block"]/tbody/tr/td/table/tbody/tr/td[1]/span'
      attendance_result_txt_matchType: 1
    - site_name: '老师站(nicept)'
      index_url: 'https://www.nicept.net/index.php'
      index_url_str: 'index'
      index_btn_xpath: '//*[@id="mainmenu"]/li[1]/a'
      login_url: 'https://www.nicept.net/login.php'
      login_url_str: 'login'
      username_input_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[1]/td[2]/input'
      password_input_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[2]/td[2]/input'
      submit_btn_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[9]/td/input[1]' 
      login_image_captcha_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[3]/td[2]/img'
      login_image_captcha_input_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[4]/td[2]/input[1]'
      login_captcha_length: 6
      attendance_btn_xpath: '//*[@id="info_block"]/tbody/tr/td/table/tbody/tr/td[1]/span/a[5]'
      attendance_text: '簽到得魔力'
      attendance_result_xpath: '//*[@id="info_block"]/tbody/tr/td/table/tbody/tr/td[1]/span'
      attendance_result_txt_matchType: 1
    - site_name: 'HDU'
      index_url: 'https://pt.hdupt.com/index.php'
      index_url_str: 'index'
      index_btn_xpath: '//*[@id="mainmenu"]/li[1]/a'
      login_url: 'https://pt.hdupt.com/login.php'
      login_url_str: 'login'
      username_input_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[1]/td[2]/input'
      password_input_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[2]/td[2]/input'
      login_image_captcha_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[3]/td[2]/img'
      login_image_captcha_input_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[4]/td[2]/input[1]'
      login_captcha_length: 6
      submit_btn_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[6]/td/input[1]' 
      attendance_btn_xpath: '//*[@id="yiqiandao"]'
      attendance_text: '[签到]'
      attendance_result_xpath: '//*[@id="yiqiandao"]'
      attendance_result_txt_matchType: 2
    - site_name: '猫站(pterclub)'
      index_url: 'https://pterclub.com/index.php'
      index_url_str: 'index'
      index_btn_xpath: '//*[@id="ddtopmenubar"]/ul/li[1]/a'
      login_url: 'https://pterclub.com/login.php'
      login_url_str: 'login'
      username_input_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[1]/td[2]/input'
      password_input_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[2]/td[2]/input'
      login_image_captcha_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[3]/td[2]/img'
      login_image_captcha_input_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[4]/td[2]/input[1]'
      login_captcha_length: 6
      submit_btn_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[10]/td/input[1]' 
      attendance_btn_xpath: '//*[@id="do-attendance"]'
      attendance_text: '签到得猫粮'
      attendance_result_xpath: '//*[@id="attendance-wrap"]'
      attendance_result_txt_matchType: 1
    - site_name: '家园(hdhome)'
      index_url: 'https://hdhome.org/index.php'
      index_url_str: 'index'
      index_btn_xpath: '//*[@id="mainmenu"]/li[1]/a'
      login_url: 'http://hdhome.org/login.php'
      login_url_str: 'login'
      username_input_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[1]/td[2]/input'
      password_input_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[2]/td[2]/input'
      login_image_captcha_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[4]/td[2]/img'
      login_image_captcha_input_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[5]/td[2]/input[1]'
      login_captcha_length: 6
      submit_btn_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[10]/td/input[1]' 
      attendance_btn_xpath: '//*[@id="info_block"]/tbody/tr/td/table/tbody/tr/td[1]/span/a[5]'
      attendance_text: '签到得魔力'
      attendance_result_xpath: '//*[@id="info_block"]/tbody/tr/td/table/tbody/tr/td[1]/span'
      attendance_result_txt_matchType: 1
    - site_name: '高清时间(hdtime)'
      index_url: 'https://hdtime.org/index.php'
      index_url_str: 'index'
      index_btn_xpath: '//*[@id="mainmenu"]/li[1]/a'
      login_url: 'https://hdtime.org/login.php'
      login_url_str: 'login'
      username_input_xpath: '//*[@id="nav_block"]/form/table/tbody/tr[1]/td[2]/input'
      password_input_xpath: '//*[@id="nav_block"]/form/table/tbody/tr[2]/td[2]/input'
      login_image_captcha_xpath: 
      login_image_captcha_input_xpath: 
      login_captcha_length: 
      submit_btn_xpath: '//*[@id="nav_block"]/form/table/tbody/tr[5]/td/input[1]'
    - site_name: '高清视界(hdarea)'
      index_url: 'https://www.hdarea.co/index.php'
      index_url_str: 'index'
      index_btn_xpath: '//*[@id="css3menu1"]/li[1]/a'
      login_url: 'https://www.hdarea.co/login.php'
      login_url_str: 'login'
      username_input_xpath: '//*[@id="username"]'
      password_input_xpath: '//*[@id="password"]'
      login_image_captcha_xpath: 
      login_image_captcha_input_xpath: 
      login_captcha_length: 
      submit_btn_xpath: '//*[@id="login"]/form[2]/p[6]/input' 
      attendance_btn_xpath: '//*[@id="sign_in"]/a'
      attendance_text: '[签到]'
      attendance_result_xpath: '//*[@id="sign_in_done"]'
      attendance_result_txt_matchType: 2
    - site_name: '烧包(ptsbao)'
      index_url: 'https://ptsbao.club/index.php'
      index_url_str: 'index'
      index_btn_xpath: '//*[@id="mainmenu"]/li[1]/a'
      login_url: 'https://ptsbao.club/login.php'
      login_url_str: 'login'
      username_input_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[1]/td[2]/input'
      password_input_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[2]/td[2]/input'
      login_image_captcha_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[3]/td[2]/img'
      login_image_captcha_input_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[4]/td[2]/input[1]'
      login_captcha_length: 6
      submit_btn_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[10]/td/input[1]' 
    - site_name: '聆音(soulvoice)'
      index_url: 'https://pt.soulvoice.club/index.php'
      index_url_str: 'index'
      index_btn_xpath: '//*[@id="mainmenu"]/li[1]/a'
      login_url: 'https://pt.soulvoice.club/login.php'
      login_url_str: 'login'
      username_input_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[1]/td[2]/input'
      password_input_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[2]/td[2]/input'
      login_image_captcha_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[3]/td[2]/img'
      login_image_captcha_input_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[4]/td[2]/input[1]'
      login_captcha_length: 6
      submit_btn_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[9]/td/input[1]' 
      attendance_btn_xpath: '//*[@id="info_block"]/tbody/tr/td/table/tbody/tr/td[1]/span/a[5]'
      attendance_text: '签到得魔力'
      attendance_result_xpath: '//*[@id="info_block"]/tbody/tr/td/table/tbody/tr/td[1]/span'
      attendance_result_txt_matchType: 2
    - site_name: '柠檬(lemonhd)'
      index_url: 'https://lemonhd.org/index.php'
      index_url_str: 'index'
      index_btn_xpath: '//*[@id="mainmenu"]/li[1]/a'
      login_url: 'https://lemonhd.org/login.php'
      login_url_str: 'login'
      username_input_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[1]/td[2]/input'
      password_input_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[2]/td[2]/input'
      login_image_captcha_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[4]/td[2]/img'
      login_image_captcha_input_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[5]/td[2]/input[1]'
      login_captcha_length: 6
      submit_btn_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[10]/td/input[1]' 
      attendance_btn_xpath: '//*[@id="signtext"]/a'
      attendance_text: '签到'
      attendance_result_xpath: '//*[@id="dayBonusAvgId"]'
    - site_name: '铂金家(pthome)'
      index_url: 'https://pthome.net/index.php'
      index_url_str: 'index'
      index_btn_xpath: '//*[@id="mainmenu"]/li[1]/a'
      login_url: 'https://pthome.net/login.php'
      login_url_str: 'login'
      username_input_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[1]/td[2]/input'
      password_input_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[2]/td[2]/input'
      login_image_captcha_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[4]/td[2]/img'
      login_image_captcha_input_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[5]/td[2]/input[1]'
      login_captcha_length: 6
      submit_btn_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[10]/td/input[1]' 
      attendance_btn_xpath: '//*[@id="info_block"]/tbody/tr/td/table/tbody/tr/td[1]/span/a[6]'
      attendance_text: '签到得魔力'
      attendance_result_xpath: '//*[@id="info_block"]/tbody/tr/td/table/tbody/tr/td[1]/span'
      attendance_result_txt_matchType: 1
    - site_name: '海胆(haidan)'
      index_url: 'https://www.haidan.video/index.php'
      index_url_str: 'index'
      index_btn_xpath: '/html/body/div[2]/div[1]/ul/li[1]/a'
      login_url: 'https://www.haidan.video/login.php'
      login_url_str: 'login'
      username_input_xpath: '/html/body/div[2]/div[1]/div/form/table/tbody/tr[1]/td[2]/input'
      password_input_xpath: '/html/body/div[2]/div[1]/div/form/table/tbody/tr[2]/td[2]/input'
      login_image_captcha_xpath: 
      login_image_captcha_input_xpath: 
      login_captcha_length: 6
      submit_btn_xpath: '/html/body/div[2]/div[1]/div/form/table/tbody/tr[7]/td/input[1]' 
      attendance_btn_xpath: '//*[@id="modalBtn"]'
      attendance_text: '每日打卡'
      attendance_result_xpath: '//*[@id="modalBtn"]'
      # attendance_result_txt_matchType: 0
    - site_name: '皇后(opencd)'
      index_url: 'https://open.cd/index.php'
      index_url_str: 'index'
      index_btn_xpath: '//*[@id="mainmenu"]/li[1]/a'
      login_url: 'https://open.cd/login.php'
      login_url_str: 'login'
      username_input_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[1]/td[2]/input'
      password_input_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[2]/td[2]/input'
      login_image_captcha_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[3]/td[2]/img'
      login_image_captcha_input_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[4]/td[2]/input[1]'
      login_captcha_length: 6
      submit_btn_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[9]/td/input[1]' 
      attendance_frame_id: 'i_signin'
      attendance_btn_xpath: '//*[@id="info_block"]/tbody/tr/td/table/tbody/tr/td[3]/div[2]/a[1]'
      attendance_text: '簽到'
      attendance_image_captcha_xpath: '//*[@id="frmSignin"]/table/tbody/tr/td/img'
      attendance_image_captcha_input_xpath: '//*[@id="imagestring"]'
      attendance_captcha_length: 6
      attendance_submit_btn_xpath: '//*[@id="ok"]'
      attendance_result_xpath: '//*[@id="info_block"]/tbody/tr/td/table/tbody/tr/td[3]/div[2]/a[1]'
    - site_name: '杜比视界(hdatmos)'
      index_url: 'https://hdatmos.club/index.php'
      index_url_str: 'index'
      index_btn_xpath: '//*[@id="mainmenu"]/li[1]/a'
      login_url: 'https://hdatmos.club/login.php'
      login_url_str: 'login'
      username_input_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[1]/td[2]/input'
      password_input_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[2]/td[2]/input'
      login_image_captcha_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[3]/td[2]/img'
      login_image_captcha_input_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[4]/td[2]/input[1]'
      login_captcha_length: 6
      submit_btn_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[9]/td/input[1]' 
      attendance_btn_xpath: '//*[@id="info_block"]/tbody/tr/td/table/tbody/tr/td[1]/span/a[6]'
      attendance_text: '签到得魔力'
      attendance_result_xpath: '//*[@id="info_block"]/tbody/tr/td/table/tbody/tr/td[1]/span'
      attendance_result_txt_matchType: 1
    - site_name: '杜比(hddolby)'
      index_url: 'https://www.hddolby.com/index.php'
      index_url_str: 'index'
      index_btn_xpath: '//*[@id="mainmenu"]/li[1]/a'
      login_url: 'https://www.hddolby.com/login.php'
      login_url_str: 'login'
      username_input_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[1]/td[2]/input'
      password_input_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[2]/td[2]/input'
      login_image_captcha_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[4]/td[2]/img'
      login_image_captcha_input_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[5]/td[2]/input[1]'
      login_captcha_length: 6
      submit_btn_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[10]/td/input[1]' 
      attendance_btn_xpath: '//*[@id="info_block"]/tbody/tr/td/table/tbody/tr/td[1]/span/a[7]'
      attendance_text: '签到得魔力'
      attendance_result_xpath: '//*[@id="info_block"]/tbody/tr/td/table/tbody/tr/td[1]/span'
      attendance_result_txt_matchType: 3
    - site_name: 'PT时间(pttime)'
      index_url: 'https://www.pttime.org/index.php'
      index_url_str: 'index'
      index_btn_xpath: '//*[@id="mainmenu"]/li[1]/a'
      login_url: 'https://www.pttime.com/login.php'
      login_url_str: 'login'
      username_input_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[1]/td[2]/input'
      password_input_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[2]/td[2]/input'
      login_image_captcha_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[4]/td[2]/img'
      login_image_captcha_input_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[5]/td[2]/input[1]'
      login_captcha_length: 6
      submit_btn_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[10]/td/input[1]' 
      attendance_btn_xpath: '//*[@id="info_block"]/tbody/tr/td/table/tbody/tr[1]/td/span/a[7]'
      attendance_text: '签到得魔力'
      attendance_result_xpath: '//*[@id="info_block"]/tbody/tr/td/table/tbody/tr[1]/td/span'
      attendance_result_txt_matchType: 4
    # - site_name: '学校(btschool)'
    #   index_url: 'https://pt.btschool.club/index.php'
    #   index_url_str: 'index'
    #   index_btn_xpath: '//*[@id="mainmenu"]/li[1]/a'
    #   login_url: 'https://pt.btschool.club/login.php'
    #   login_url_str: 'login'
    #   username_input_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[1]/td[2]/input'
    #   password_input_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[2]/td[2]/input'
    #   login_image_captcha_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[3]/td[2]/img'
    #   login_image_captcha_input_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[4]/td[2]/input[1]'
    #   login_captcha_length: 6
    #   submit_btn_xpath: '//*[@id="nav_block"]/form[2]/table/tbody/tr[9]/td/input[1]' 
    #   attendance_btn_xpath: '//*[@id="outer"]/p/table/tbody/tr/td/b/a'
    #   attendance_text: '每日签到'
    #   attendance_image_captcha_xpath: 
    #   attendance_image_captcha_input_xpath: 
    #   attendance_captcha_length: 
    #   attendance_submit_btn_xpath: 